title: Md Hamidur Rahman
email: hamidur.rahman@utexas.edu
description: >-
  Transportation Planning, Accessibility, and Spatial Data
theme: jekyll-theme-slate

# Social links
github_username: mdh-rahman
linkedin_username: mdrahman13

# Navigation links
header_pages:
  - index.md
  - projects.md
  - maps.md
  - photos.md
  - writing.md
